export const HTTP_STATUS = {
  CREATED: 201,
  OK: 200,
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
};

export const RESPONSE_CODE = {
  CREATED: "CREATED",
  OK: "OK",
  NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
};
